### ISSUE TITLE
Unexpected panic when specifying certain files

### ISSUE THREAD

**Issue by brsmsn** [azohra/lyra#1]
## Bug Description

Lyra panics when specifying invalid files.

Files similar to these will panic:
* Empty files.
* Auth params too short/long or are simply invalid such as a single char.
---
* OS: MacOS 10.12.6
* Go Version: `go version go1.10 darwin/amd64`
* Output:
```
⋊> ~/g/s/g/a/lyra on dev ⨯ ./lyra decrypt aae 
Enter passphrase: 
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/azohra/lyra/pkg/lfile.(*SecureLyraFile).ParseFile(0xc42008e190, 0x7fff5fbffc3f, 0x3, 0x0, 0x0)
	/Users//go/src/github.com/azohra/lyra/pkg/lfile/secure_lyra_file.go:111 +0x40a
github.com/azohra/lyra/pkg/lfile.NewParsedSLFile(0x7fff5fbffc3f, 0x3, 0xc4200160a0, 0xc420053d60, 0x1040938)
	/Users//go/src/github.com/azohra/lyra/pkg/lfile/secure_lyra_file.go:36 +0x58
main.decrypt(0x7fff5fbffc3f, 0x3, 0x0, 0x0, 0x0, 0xc4200160a0, 0x1, 0x8, 0x112d200, 0x0)
	/Users//go/src/github.com/azohra/lyra/cmd/lyra/decrypt.go:113 +0x39
main.(*decryptcmd).Run(0xc42000e3c0, 0xc42000e0e0, 0x1, 0x1, 0x0, 0x0)
	/Users//go/src/github.com/azohra/lyra/cmd/lyra/decrypt.go:96 +0xe2
main.main()
	/Users//go/src/github.com/azohra/lyra/cmd/lyra/lyra.go:110 +0x3dd

```

## Steps to Reproduce

1. Create an empty file and/or a file that has an invalid auth parameter
2. `lyra decrypt` file

**Comment by brsmsn** [comment]
Fixed in GH-2
